name: Bug report
description: Report a reproducible defect
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report. Please include enough detail to reproduce the issue.

  - type: input
    id: area
    attributes:
      label: Affected area
      description: Site, CLI, extension, scripts, or docs
      placeholder: "CLI"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Include commands, inputs, and environment details
      placeholder: |
        1. Run ...
        2. Run ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Paste relevant output (sanitize secrets)
      render: shell
