name: Question
description: Ask about usage, setup, or contributor workflow.
title: "[Question] "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Ask a usage or contribution question. For vulnerabilities, use private reporting from SECURITY.md.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
      placeholder: I am trying to...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Share relevant commands, logs, or environment details.
      placeholder: Node version, OS, command output, etc.
  - type: textarea
    id: attempted
    attributes:
      label: What you tried
      description: List actions you already attempted.
      placeholder: I ran...

